# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone SE",
  "iPhone 8",
  "iPhone X",
  "iPad Pro (10.5-inch)"
])

languages([
  "en-US"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments("-favColor red")

# The name of the scheme which contains the UI Tests
scheme "OpenShop"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true # clear all previously generated screenshots before creating new ones

reinstall_app true
app_identifier "businessfactory.openshop"

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./OpenShop.xcworkspace"

# For more information about all available options run
# snapshot --help

number_of_retries 3